export enum TOKEN_TYPES {
  SIGNIN_TOKEN = 'SIGNIN_TOKEN',
  RESET_PASSWORD_TOKEN = 'RESET_PASSWORD_TOKEN',
}

export enum AUTH_PROVIDER {
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  CUSTOM = 'CUSTOM',
}
