export enum USER_ROLES {
  SUPER_ADMIN = "SUPER_ADMIN",
  MANAGER = "MANAGER",
  ENGINEER = "ENGINEER",
  VIEWER = "VIEWER",
}

export enum USER_STATUS {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING",
  UNAPPROVED = "UNAPPROVED",
}

export const NOT_ALLOWED_USERS = [
  USER_STATUS.INACTIVE,
  USER_STATUS.UNAPPROVED,
  USER_STATUS.PENDING,
];
